#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

diff=$(npm run prettier)

allOk='All matched files use Prettier code style!'

echo "sss"
echo $diff
echo "eee"

if [[ "$diff" == *"$allOk"* ]]
then
    echo "All ok"
    exit 0
else
    echo "Please commit prettified files and try to push again."
    exit 1
fi